# Generated by Django 2.2.7 on 2019-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191111_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rigion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
