# Generated by Django 2.1 on 2019-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_rigion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blood',
            field=models.CharField(max_length=100),
        ),
    ]
