# Generated by Django 2.1 on 2019-11-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('cell', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
